version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/library?sslmode=disable
    networks:
      - library-network
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: library-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network
    restart: unless-stopped

networks:
  library-network:
    driver: bridge

volumes:
  postgres-data: